# 第4章 Numpy基础：数组与向量化计算

In [3]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))
print("---------np---------")
%time for _ in range(10): my_arr2 = my_arr * 2
print("---------builtin-----------")
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]



---------np---------
CPU times: user 23.4 ms, sys: 294 µs, total: 23.7 ms
Wall time: 22.9 ms
---------builtin-----------


CPU times: user 676 ms, sys: 164 ms, total: 840 ms
Wall time: 877 ms


In [12]:
data = np.random.randn(2, 3)
print(data)
print(data * 10)
print(data + data)
print(data.shape)
print(data.dtype)
print(type(data))


[[ 1.35729254  0.7604816   1.45567086]
 [ 0.65816685 -0.69008919  0.32973979]]
[[13.57292543  7.60481596 14.55670865]
 [ 6.58166854 -6.90089192  3.29739795]]
[[ 2.71458509  1.52096319  2.91134173]
 [ 1.31633371 -1.38017838  0.65947959]]
(2, 3)
float64
<class 'numpy.ndarray'>


In [22]:
# 生成ndarray
data = [6, 5, 7, 8]
arr = np.array(data)
print(arr, type(arr))
arr
arr = np.arange(8).reshape((2, 4))
arr

[6 5 7 8] <class 'numpy.ndarray'>


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.ones(10)
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [44]:
np.empty(5)
np.empty((3, 5))

array([[0.        , 0.        , 0.4472136 , 0.0531494 , 0.18257419],
       [0.4472136 , 0.2125976 , 0.36514837, 0.4472136 , 0.4783446 ],
       [0.54772256, 0.4472136 , 0.85039041, 0.73029674, 0.4472136 ]])

In [48]:
arr
arr.dtype

dtype('int64')

In [51]:
arr = arr.astype(np.float64)
arr.dtype

dtype('float64')

In [55]:
int_arr = np.arange(10)
float_arr = np.array([0.1, 0.2], dtype=np.float64)
print(float_arr, int_arr)
int_arr = int_arr.astype(float_arr.dtype)
print(int_arr.dtype)

[0.1 0.2] [0 1 2 3 4 5 6 7 8 9]
float64


In [58]:
np.empty(8, dtype='u4')

array([6, 0, 5, 0, 7, 0, 8, 0], dtype=uint32)

### 数组算术、基础索引与切片、布尔索引

In [83]:
arr = np.arange(1, 10).reshape(3, 3)
print(arr)
print(arr * arr)
print(arr - arr)
print(1 / arr)
print(arr >= arr)
print(arr[0:2, 0:2])
print(arr[1][1])
print(arr[1, 1])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]
 [0.14285714 0.125      0.11111111]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[1 2]
 [4 5]]
5
5


In [95]:
arr3d = np.arange(1, 13).reshape((2, 2, 3))
print(arr3d)

old_arr0 = arr3d[0].copy()
print(old_arr0)
arr3d[0] = 42
print(arr3d)
arr3d[0] = old_arr0
print(arr3d)
print(arr3d[1, 0])


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[1 2 3]
 [4 5 6]]
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[7 8 9]


In [113]:
arr2d = np.arange(1, 13).reshape((3, 4))
print(arr2d)
print(arr2d[:2])
print(arr2d[:2, 1:])
print(arr2d[1, :2])
print(arr2d[:2, 2])
print(arr2d[:, 2])
print(arr2d[:, :2])
print(arr2d[:, :1])
print(arr2d[:, 0])
print(arr2d[:, :0])
arr2d[:2, 1:] = 0
print(arr2d)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3 4]
 [5 6 7 8]]
[[2 3 4]
 [6 7 8]]
[5 6]
[3 7]
[ 3  7 11]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[1]
 [5]
 [9]]
[1 5 9]
[]
[[ 1  0  0  0]
 [ 5  0  0  0]
 [ 9 10 11 12]]


In [128]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(names)
print(data)
print(data[names == 'Bob'])
print(data[names == 'Bob', 2:])
print(data[names == 'Bob', 3])
print(names != 'Bob')
print(data[names != 'Bob'])
print(~(names == 'Bob'))
print(data[~(names == 'Bob')])

# Python的关键字and和or对布尔值数组并没有用，只能使用 & 和 | 来代替。
mask = (names == 'Bob') | (names == 'Will')
print(mask)
print(data[data < 0])
data[data < 0] = 0
print(data)
data[names != 'Joe'] = 7
print(data)


['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 1.08242952 -0.95645674  0.44963277  1.1372564 ]
 [ 1.49730423 -0.78768223 -1.45899633 -0.01416095]
 [ 0.58014908  2.00953513 -0.59485909 -1.52061163]
 [ 0.56923112 -2.15620642 -0.45816494 -0.92446478]
 [-0.79051119  1.24054449 -1.42670537  0.56280069]
 [-0.77698944  0.48128837  1.13360837  1.30442087]
 [ 1.38586106 -1.82775817 -1.51841996 -0.23194122]]
[[ 1.08242952 -0.95645674  0.44963277  1.1372564 ]
 [ 0.56923112 -2.15620642 -0.45816494 -0.92446478]]
[[ 0.44963277  1.1372564 ]
 [-0.45816494 -0.92446478]]
[ 1.1372564  -0.92446478]
[False  True  True False  True  True  True]
[[ 1.49730423 -0.78768223 -1.45899633 -0.01416095]
 [ 0.58014908  2.00953513 -0.59485909 -1.52061163]
 [-0.79051119  1.24054449 -1.42670537  0.56280069]
 [-0.77698944  0.48128837  1.13360837  1.30442087]
 [ 1.38586106 -1.82775817 -1.51841996 -0.23194122]]
[False  True  True False  True  True  True]
[[ 1.49730423 -0.78768223 -1.45899633 -0.01416095]
 [ 0.58014908  2.

### 神奇索引